# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "BYU STEM Camp Light the Y"
short_title: -Badge
# class_number: ECEN 330
email: jgoeders@byu.edu
host: localhost
baseurl: "/light-the-y"
url: "https://y-badge.github.io"
github:
  url: https://github.com/y-badge/light-the-y
  # fileurl: https://github.com/byu-cpe/ecen330_student/blob/main

show_construction_message: false
construction_message: These lab pages are under construction and subject to change for the Fall 2022 semester.

permalink: pretty

markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  setup:
    output: true
    permalink: /:collection/:name/
    sort_by: number
  modules:
    output: true
    permalink: /:collection/:name/
  documentation:
    output: true
    permalink: /:collection/:name/
    sort_by: number
  other:
    output: true
    permalink: /:collection/:name/
    sort_by: number
  pages:
    output: true
    permalink: /:name/
    order:
      - overview.md
      - goals.md
      - lab_setup.md

exclude:
  - icon.ai
  - Dockerfile
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-sitemap
  - jekyll-pdf-embed
